### ISSUE TITLE
frontend fetch

### ISSUE THREAD

**Issue by Karyum** [mjmajadly/WebAhead#10]
this is a nice thing to have and a good practice for abstraction

how about making an abstraction for the fetch, so that if in the future you would want to use the fetch again. 
then you would call that function again with different parameters for example `fetchWrapper(url, method, body)`

otherwise nice clean code

**Comment by mjmajadly** [comment]
![EUZ9ypkUYAAWqrk](https://user-images.githubusercontent.com/43019810/98919340-58201c00-24d7-11eb-9d1a-f0d65a2c4b15.jpg)

**Comment by mjmajadly** [comment]
![Capture](https://user-images.githubusercontent.com/43019810/98936853-3ed69a00-24ee-11eb-8f1c-c2437ef395de.PNG)

**Comment by Karyum** [comment]
we can do this even better, either by passing a callback to the fetchWrapper or returning a promise from it. because then we can use it anywhere
