### ISSUE TITLE
where do I start?

### ISSUE THREAD

**Issue by MorisR** [mjmajadly/WebAhead#6]
the project should include a clear starting point,
traditionally an "index.js" file is included in the root directory of the project (and sometimes even in directories like src/server) to indicate the starting point of that project/directory/etc..

it is even stated in the ```package.json``` file:
https://github.com/mjmajadly/WebAhead/blob/74e38347c03a8eba1d2a2cf00f24898a15ab7e5a/Week6/searchBox-self-workin/package.json#L5

**Comment by mjmajadly** [comment]
changed it to server.js
