### ISSUE TITLE
refactor suggestion - calling the  missingHandler.js to avoid code repetition

### ISSUE THREAD

**Issue by MorisR** [mjmajadly/WebAhead#7]
You can call the [missingHandler.js](https://github.com/mjmajadly/WebAhead/blob/main/Week6/searchBox-self-workin/server/handlers/missingHandler.js) function here to avoid repetition: 

https://github.com/mjmajadly/WebAhead/blob/74e38347c03a8eba1d2a2cf00f24898a15ab7e5a/Week6/searchBox-self-workin/server/handlers/publicHandler.js#L20-L23

https://github.com/mjmajadly/WebAhead/blob/74e38347c03a8eba1d2a2cf00f24898a15ab7e5a/Week6/searchBox-self-workin/server/handlers/homeHandler.js#L8-L10

https://github.com/mjmajadly/WebAhead/blob/74e38347c03a8eba1d2a2cf00f24898a15ab7e5a/Week6/searchBox-self-workin/server/handlers/dataHandler.js#L7-L10

**Comment by MorisR** [comment]
you should also set the status code to 404 in "homeHandler.js" and "dataHandler.js"

**Comment by mjmajadly** [comment]
done, used the MissingHandler everywhere and set the status code to 404
