### ISSUE TITLE
variable is redundant

### ISSUE THREAD

**Issue by MorisR** [mjmajadly/WebAhead#8]
the "elem" variable is redundant, you could use the "element" argument directly

https://github.com/mjmajadly/WebAhead/blob/74e38347c03a8eba1d2a2cf00f24898a15ab7e5a/Week6/searchBox-self-workin/public/index.js#L8-L11

** I also suggest adding a check for null/undefined ( because a null value could be passed to the function and cause it to fail)

**Comment by mjmajadly** [comment]
this was written by a team member for the autocomplete section. removed it :)
